### ISSUE TITLE
Nitro externalized package has incorrect main entry point

### ISSUE THREAD

**Issue by mahdiboomeri** [nuxt/framework#7105]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.7.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `pnpm@7.9.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/image-edge@1.0.0-27657146.da85542`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/mahdiboomeri/nuxt3-externalized-issue

### Describe the bug

When using `jsonwebtoken` with `@nuxt/image` which both depend on `semver` package, on the build step nitro tries to use the latest version.
In the server bundle `main` entry of semver's package.json points to `index.js` but the index file is `semver.js`.

### Additional context

The reproduction uses rc8 but I also tested the issue with the edge channel.

### Logs

```shell
# in the build step
WARN  Multiple major versions of package semver are being externalized. Picking latest version.                        14:58:38
  - /path/to/project/nuxt-semver-issue/node_modules/.pnpm/jsonwebtoken@8.5.1/node_modules/semver@5.7.1
  - /path/to/project/nuxt-semver-issue/node_modules/.pnpm/sharp@0.30.7/node_modules/semver@7.3.7

# when running node .output/server/index.mjs  
[nuxt] [request error] [unhandled] [500] Cannot find module '/path/to/project/nuxt-semver-issue/.output/server/node_modules/semver/index.js'. Please verify that the package.json has a valid "main" entry
  at tryPackage (node:internal/modules/cjs/loader:364:19)  
  at Module._findPath (node:internal/modules/cjs/loader:577:18)  
  at Module._resolveFilename (node:internal/modules/cjs/loader:942:27)  
  at Module._load (node:internal/modules/cjs/loader:804:27)  
  at Module.require (node:internal/modules/cjs/loader:1022:19)  
  at require (node:internal/modules/cjs/helpers:102:18)  
  at Object.<anonymous> (./.output/server/node_modules/jsonwebtoken/lib/psSupported.js:1:14)  
  at Module._compile (node:internal/modules/cjs/loader:1120:14)  
  at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)  
  at Module.load (node:internal/modules/cjs/loader:998:32)
```

**Comment by smorcuend** [comment]
Same issue here with: https://www.npmjs.com/package/jose
```
[nuxt] [request error] [unhandled] [500] Cannot find module '/path/to/project/.output/server/node_modules/jose/dist/node/cjs/index.js'
  at createEsmNotFoundErr (node:internal/modules/cjs/loader:983:15)  
  at finalizeEsmResolution (node:internal/modules/cjs/loader:976:15)  
  at resolveExports (node:internal/modules/cjs/loader:493:14)  
  at Function.Module._findPath (node:internal/modules/cjs/loader:533:31)  
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:942:27)  
  at Function.Module._load (node:internal/modules/cjs/loader:804:27)  
  at Module.require (node:internal/modules/cjs/loader:1028:19)  
  at require (node:internal/modules/cjs/helpers:102:18)  
  at Object.<anonymous> (./server/node_modules/jwks-rsa/src/utils.js:1:14)  
  at Module._compile (node:internal/modules/cjs/loader:1126:14)
```

Server compilation generates /path/to/project/.output/server/node_modules/jose/dist/node/esm/index.js

**Comment by mahdiboomeri** [comment]
workaround until the issue resolves.

```typescript
import path from 'node:path';
import { promises as fs } from 'node:fs';
import type { Nitro } from 'nitropack';

import { defineNuxtConfig } from 'nuxt';

export default defineNuxtConfig({
  nitro: {
    hooks: {
      async compiled(nitro: Nitro) {
        const packagePath = path.join(
          nitro.options.output.dir,
          'server',
          'node_modules',
          'semver',
          'package.json'
        );
        const packageContent = await fs.readFile(
          packagePath,
          'utf-8'
        );

        await fs.writeFile(
          packagePath,
          packageContent.replace(
            '"main": "index.js"',
            '"main": "semver.js"'
          )
        );
      },
    },
  },
});

```

**Comment by huang-julien** [comment]
Almost same issue with `nuxt-runtime-compiler` module. It adds vue to rollup dynamicRequireTarget. At build, Nitro send `vue/server-renderer/index.mjs` to the `.output/server/node_modules`.
 When vue try to `const { ssrRenderAttrs: _ssrRenderAttrs } = require("vue/server-renderer")`, it throws
 ```
[nuxt] [request error] [unhandled] [500] Cannot find module 'D:\GIT\nuxt3-runtime-compiler-module\playground\.output\server\node_modules\vue\server-renderer\index.js
```

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the next RC.

Let me know if not and I'll reopen.

**Comment by sig9** [comment]
Having this issue with latest nuxt framework  https://github.com/nuxt/framework/commit/2894a75bc8cd6430a5945f411a8e79dac67288a5 
after bringing in @nuxt/image-edge "^1.0.0-27719579.87dcdf2"

**Comment by mahdiboomeri** [comment]
@danielroe Hey, It seems like the issue isn't resolved (RC 11). This time the `semver.js` isn't generated.
I've updated my [reproduction](https://github.com/mahdiboomeri/nuxt3-externalized-issue).

**Comment by hamidooChe** [comment]
> This should be resolved in the [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/), or in the next RC.
> 
> Let me know if not and I'll reopen.

Even after [this fix](https://github.com/unjs/nitro/pull/515), overriding an older version can provoke error in case of using another module that depends on overrided version, so forcing newer version can lead to incompatibility problems (googleapis and jsonwebtoken use jwa with different versions for example) maybe adding an option to disable trace for nested modules would be temporarily a solution

**Comment by pixelspark** [comment]
I am seeing this issue still with rc12. The below error is generated for multiple packages:

````
 WARN  Multiple major versions of package parse5 are being externalized. Picking latest version:                                                        14:37:18

  - /xxx/node_modules/parse5@5.1.1
  + /xxx/node_modules/parse5-htmlparser2-tree-adapter/node_modules/parse5@6.0.1
````

Then at `nuxi preview`:

````
Nuxi 3.0.0-rc.12                                                                                                                                        14:37:23
ℹ Node.js version: 18.10.0                                                                                                                              14:37:23
ℹ Preset: node-server                                                                                                                                   14:37:23
ℹ Working dir: .output                                                                                                                                  14:37:23
ℹ Loading .env. This will not be loaded when running the server in production.                                                                          14:37:23
ℹ Starting preview command: node ./server/index.mjs                                                                                                     14:37:23
                                                                                                                                                        14:37:23
node:internal/modules/cjs/loader:393
      const err = new Error(
                  ^

Error: Cannot find module '/xxx/.output/server/node_modules/parse5/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:393:19)
    at Module._findPath (node:internal/modules/cjs/loader:606:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:971:27)
    at Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1051:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/xxx/.output/server/node_modules/cli-highlight/dist/index.js:30:27)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/xxx/.output/server/node_modules/parse5/package.json',
  requestPath: 'parse5'
}

Node.js v18.10.0

 ERROR  Command failed with exit code 1: node ./server/index.mjs                                                                                        14:37:23

  at makeError (node_modules/nuxi/dist/shared/nuxi.bc8d057a.mjs:619:11)
  at handlePromise (node_modules/nuxi/dist/shared/nuxi.bc8d057a.mjs:1026:26)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.invoke (node_modules/nuxi/dist/chunks/preview.mjs:63:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
````

`npm ls parse5`:

````
xxx @ /xxx
└─┬ typeorm@0.3.10
  └─┬ cli-highlight@2.1.11
    ├─┬ parse5-htmlparser2-tree-adapter@6.0.1
    │ └── parse5@6.0.1
    └── parse5@5.1.1
````

Same happens for packages `pako`, `uuid`, `readable-stream`, `@xmldom/xmldom` and `tslib`. Possibly these changed their module formats between major versions, and that is throwing the compiler off?

**Comment by NtchPlayer** [comment]
Hi same problem here with js-cookie.

In my case, this module at the same time by amazon-cognito-identity-js (2.2.1) and i18n (3.0.1 = last version).

When my app is build I have this error:
ERROR [nuxt] [request error] Cannot find module '/var/task/.output/server/node_modules/js-cookie/dist/js.cookie.js'.

I don't know if a fix can be planned ? 🤔

**Comment by mastercoding** [comment]
This happens for me with a few packages, `semver`, `lru-cache`, `jws`, `yallist` and `jwa`. 

I understand the issue is not related to specific packages, but I wanted to post them here anyway for other people that encounter the same issue. I'm using the edge release (currently 3.0.0-rc.13-27781436.1f6b3be).

**Comment by AlexRoehm** [comment]
Having exact same issue as pixelspark with `parse5` using `rc9`, `rc11` or `rc11`

**Comment by itpropro** [comment]
Multiple people seem to have this problem with the mongodb package and the dependent `whatwg-url` package:

https://stackoverflow.com/questions/72718506/nuxt-js-3-application-with-mongoose-mongodb-not-starting-in-production
https://github.com/unjs/nitro/issues/612

any updates @danielroe ?

**Comment by NtchPlayer** [comment]
Hi,
Anyone found a solution temporary to solve this issue ?

I try to force package 'amazon-cognito-identity-js' to work with 'js-cookie' 3.0.1 with ['overrides' rule of npm](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) but It's not working :(

**Comment by AlexRoehm** [comment]
As for me the problem is, that some modules are not copied during the build process. I was able to solve it with the following code within nuxt.config.ts:
`nitro: {
    hooks: {
      compiled(nitro: Nitro) {
        const packages = []
        packages.push({
          dest:path.join(
          nitro.options.output.dir,
          'server',
          'node_modules',
          'parse5'),
          src: path.join(
          '.',
          'node_modules',
          'parse5',
          'dist',
          'cjs')
        })
        packages.push({
          dest:path.join(
          nitro.options.output.dir,
          'server',
          'node_modules',
          'entities'),
          src: path.join(
          '.',
          'node_modules',
          'entities')
        })
        try {
          packages.forEach(pack => {
            fs.copySync(pack.src, pack.dest, {overwrite: true})           
          });
        } catch (err) {}
      },
    },`

**Comment by pixelspark** [comment]
> I am seeing this issue still with rc12. The below error is generated for multiple packages:

Still seeing it in v3.0. 

> Hi, Anyone found a solution temporary to solve this issue ?
> 
> I try to force package 'amazon-cognito-identity-js' to work with 'js-cookie' 3.0.1 with ['overrides' rule of npm](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) but It's not working :(

I also experienced `npm overrides` not doing what it is advertised to do. Looks like it only really works without a `package-lock.json` and without existing `node_modules`? 

I managed to reduce the number of dependencies that have this problem and have also filed an issue with one of the packages using an older version of a dependency to get them to upgrade. My solution for the one remaining package (`parse5`) that caused me issues was to hand-edit package-lock.json. I simply copy-paste the version, URL and integrity hash fields to ensure only a single version of it is ever used. Each time I do an `npm upgrade` I have to hand-edit the lockfile again, but then it works and is relatively easy.

**Comment by franzos** [comment]
I'm facing the same issue on `v3.0.0`.

Build:

```bash
 WARN  Multiple major versions of package parse5 are being externalized. Picking latest version:             21:57:36

  - /client/node_modules/parse5@5.1.1
  + /client/node_modules/parse5-htmlparser2-tree-adapter/node_modules/parse5@6.0.1


 WARN  Multiple major versions of package parse5 are being externalized. Picking latest version:             21:57:36

  + /client/node_modules/parse5-htmlparser2-tree-adapter/node_modules/parse5@6.0.1
  - /client/node_modules/parse5@5.1.1
```

Run:

```bash
node .output/server/index.mjs
Listening http://[::]:3000
[nuxt] [request error] [unhandled] [500] Cannot find module '/client/.output/server/node_modules/parse5/lib/index.js'. Please verify that the package.json has a valid "main" entry
```

I have already tried multiple steps including externalizing without much luck:

```bash
build: {
            transpile: ['typeorm', 'parse5', 'cli-highlight']
```

I got a little bored of this issue, and decided for the hammer-approach:

```
cp -r node_modules/parse5/lib/ .output/server/node_modules/parse5/lib
```

Works fine for now.

**Comment by mctweb** [comment]
``` 
Nov 25, 06:08:37 PM: 96ffbbd9 ERROR  [nuxt] [request error] [unhandled] [500] Cannot find module '/var/task/.netlify/functions-internal/server/node_modules/semver/index.js'. Please verify that the package.json has a valid "main" entry
  at tryPackage (node:internal/modules/cjs/loader:353:19)  
  at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)  
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)  
  at Function.Module._load (node:internal/modules/cjs/loader:778:27)  
  at Module.require (node:internal/modules/cjs/loader:1005:19)  
  at require (node:internal/modules/cjs/helpers:102:18)  
  at Object.<anonymous> (./.netlify/functions-internal/server/node_modules/jsonwebtoken/lib/psSupported.js:1:14)  
  at Module._compile (node:internal/modules/cjs/loader:1105:14)  
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)  
  at Module.load (node:internal/modules/cjs/loader:981:32)
```
I have this issue when using `firebase/auth` and `@nuxt/image-edge` and deploying to netlify with nuxi build. It works when using nuxi generate and nuxi dev. Removing `@nuxt/image-edge` fixed this problem

**Comment by andresmeidla** [comment]
in case you have the semver conflict with the jsonwebtoken package, you might be able to work around it with downgrading it:
`npm i -D jsonwebtoken@7`
