### ISSUE TITLE
Nitropack server fails

### ISSUE THREAD

**Issue by nandi95** [nuxt/framework#4177]
### Environment

```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.8.0`
- Nuxt Version:     `3.0.0-27489107.7379184`
- Package Manager:  `npm@8.5.5`
- Builder:          `vite`
- User Config:      `publicRuntimeConfig`, `srcDir`, `typescript`, `modules`, `meta`, `css`
- Runtime Modules:  `~/modules/app-customisations.ts`, `@nuxtjs/tailwindcss@5.0.2`
- Build Modules:    `-`
------------------------------
```

### Reproduction

1. clone - https://github.com/nandi95/nuxt-starter
2. run `npm ci && nuxi upgrade` (upgrade should give you [this compare](https://github.com/nuxt/framework/compare/ec32cf9...7379184))

### Describe the bug

Nitropack server fails:
with ssr on it displays the error:
<img width="528" alt="Screenshot 2022-04-07 at 18 27 17" src="https://user-images.githubusercontent.com/41805560/162261845-b142bbf0-0901-4c35-9aaf-143cba70e244.png">
with ssr off, it displays this error:
<img width="462" alt="Screenshot 2022-04-07 at 18 28 27" src="https://user-images.githubusercontent.com/41805560/162262023-a3b02c44-3c7d-406b-a306-d81fbd33a678.png">

### Additional context

I think this is caused by https://github.com/nuxt/framework/commit/11626eea4f8801e9accc632225c6c54ed4bb69a1#diff-697dbfc0fc13b7a07a647ed5d0ba99e9b5d5e83d6eb78e53b05d97b3a6dec94aR98

**Comment by pi0** [comment]
Hi, @nandi95. Going back to this issue, it seems directly from vite's dist bundle and `@upfrontjs/framework` library trying to access `.merge` from a CommonJS library and I don't have access to the source (`index.min.js` is minified and obfusticated).

**Comment by nandi95** [comment]
Huh, That's coming from here: https://github.com/upfrontjs/framework/blob/main/src/Support/GlobalConfig.ts#L28
but that doesn't explain why it is the way it is without ssr no?
Without it the console also reports:
` ERROR  Rollup error:  Error: Cannot find module /Users/user_name/Web/nuxt-starter/.nuxt/dist/server/server.mjs imported from...`

**Comment by pi0** [comment]
> Without it the console also reports:
ERROR Rollup error: Error: Cannot find module /Users/user_name/Web/nuxt-starter/.nuxt/dist/server/server.mjs imported from...

Oh this regression is just solved. Recreate lockfile to get it fixed...


Still server build issue with vite remains... If you have control, avoid using lodash for js lib. Defu can be used instead 😊

**Comment by nandi95** [comment]
I suspect `@karnama/vueish` will also have similar issues. Will look into it and into [defu](https://www.npmjs.com/package/defu).
Looking forward to that merge.

**Comment by danielroe** [comment]
This seems to be working now. Let me know if not and I can reopen.
