### ISSUE TITLE
Error 'Cannot find module' when add server plugin from module on edge version.

### ISSUE THREAD

**Issue by TenshiGoan** [nuxt/framework#9577]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.1-rc.0-27838776.d0c0cd7`
- Nitro Version:    `1.0.1-27840616.e4ed8d2`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Working in current release(3.0.0)
https://stackblitz.com/edit/github-jtwwyj-ziwsj3

Error in edge(3.0.1-rc):
https://stackblitz.com/edit/github-jtwwyj

### Describe the bug

addServerPlugin don't find files without extension.
When i use extension i see error like "[worker reload] [worker init] Unknown file extension ".ts" for /home/projects/github-jtwwyj/src/runtime/nitro.ts"

### Logs

```shell
Nuxi 3.0.1-rc.0-27838776.d0c0cd7                                                                                                    05:34:46
Nuxt 3.0.1-rc.0-27838776.d0c0cd7 with Nitro 1.0.1-27840616.e4ed8d2                                                                  05:34:46
                                                                                                                                    05:34:49
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.1.104:3000/


 WARN  'file:///home/projects/github-jtwwyj/src/runtime/nitro' is imported by virtual:#internal/nitro/virtual/plugins, but could not be resolved – treating it as an external dependency

✔ Nitro built in 1111 ms                                                                                                      nitro 05:34:55
ℹ Vite client warmed up in 3234ms                                                                                                   05:34:56

 ERROR  [worker reload] [worker init] Cannot find module '/home/projects/github-jtwwyj/src/runtime/nitro' imported from /home/projects/github-jtwwyj/playground/.nuxt/dev/index.mjs

  at InternalError.get (https://githubjtwwyj-i3pq.w-corp.staticblitz.com/blitz.8cf5a3c77f45c942df800a39619ec49fff7e5814.js:6:292488)
  at https://githubjtwwyj-i3pq.w-corp.staticblitz.com/blitz.8cf5a3c77f45c942df800a39619ec49fff7e5814.js:6:974455
  at Array.forEach (<anonymous>)
  at TryGetAllProperties (https://githubjtwwyj-i3pq.w-corp.staticblitz.com/blitz.8cf5a3c77f45c942df800a39619ec49fff7e5814.js:6:974363)
  at serializeError (https://githubjtwwyj-i3pq.w-corp.staticblitz.com/blitz.8cf5a3c77f45c942df800a39619ec49fff7e5814.js:6:975040)
  at process.workerOnGlobalUncaughtException [as _fatalException] (https://githubjtwwyj-i3pq.w-corp.staticblitz.com/blitz.8cf5a3c77f45c942df800a39619ec49fff7e5814.js:6:1605143)
  at Object.triggerUncaughtException (https://githubjtwwyj-i3pq.w-corp.staticblitz.com/blitz.8cf5a3c77f45c942df800a39619ec49fff7e5814.js:15:362743)
  at i.loadESM (https://githubjtwwyj-i3pq.w-corp.staticblitz.com/blitz.8cf5a3c77f45c942df800a39619ec49fff7e5814.js:6:246694)
  at async handleMainPromise (https://githubjtwwyj-i3pq.w-corp.staticblitz.com/blitz.8cf5a3c77f45c942df800a39619ec49fff7e5814.js:6:989059)
```

**Comment by otomad** [comment]
Same problem in edge version.

It doesn't seem to allow **ts** external nitro plugins, but **js** or **mjs** does.
