### PR TITLE
feat(nuxt): support vue runtime compiler

### PR DESCRIPTION
**Pull request by huang-julien**
### 🔗 Linked issue

resolve nuxt/nuxt.js#13843 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR allow to use vue runtimeCompiler on both server and client side

- add vue.runtimeCompiler boolean option to nuxt/schema
- unmock vue 3 only when runtimeCompiler option is set to true when building and make vue runtime compiler available client side
- with externalVue to true, force trace files used by generated code from the runtime compiler

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
Hi @huang-julien and thanks for this PR! 💚  I think finally we can add an option to nitro if modification of commonJS plugin options is required. 

I hope we can add runtime support with lighter dependencies. At least having `@vue/devtools-api` doesn't makes sense to me in the bundle for it.

(BTW: You don't need to merge into main on each commit. I will make once rebase before merge)

**Comment by huang-julien** [comment]
> Hi @huang-julien and thanks for this PR! 💚 I think finally we can add an option to nitro if modification of commonJS plugin options is required.
> 
> I hope we can add runtime support with lighter dependencies. At least having `@vue/devtools-api` doesn't makes sense to me in the bundle for it.
> 
> (BTW: You don't need to merge into main on each commit. I will make once rebase before merge)

Hi @pi0  \:wave:  , yes i was thinking about a PR on Nitro to add the option for the commonjs plugin modification instead of just replacing it in the nuxt package. Do you want me to remove the @vue/devtool-api from the bundle through a commit ?

**Comment by huang-julien** [comment]
without the runtimeCompiler : Total size: 3.16 MB (410 kB gzip)
with @vue/devtools : Σ Total size: 5.19 MB (564 kB gzip)
without @vue/devtools : Σ Total size: 5.14 MB (559 kB gzip)

That's quite heavy ...

**Comment by huang-julien** [comment]
linked PR - https://github.com/unjs/nitro/pull/187
the feature will be refactored if the PR is accepted

File: packages/nuxt/src/core/nitro.ts [hunk 1]
```diff
@@ -121,6 +131,16 @@ export async function initNitro (nuxt: Nuxt) {
     nitro.options.rollupConfig.plugins.push(plugin)
   })
 
+  // Enable runtime compiler on build
+  if (nuxt.options.runtimeCompiler && !nuxt.options.dev) {
+    // set vue esm on client
+    nuxt.hook('vite:extendConfig', (config, { isClient }) => {
+      if (isClient) {
+        config.resolve.alias.vue = 'vue/dist/vue.esm-bundler'
```
Comment (pi0) [inline packages/nuxt/src/core/nitro.ts:139]: Shall we support client alias for webpack too?

File: packages/nuxt/package.json [hunk 2]
```diff
@@ -36,6 +36,8 @@
     "@nuxt/telemetry": "^2.1.3",
     "@nuxt/ui-templates": "^0.1.0",
     "@nuxt/vite-builder": "^3.0.0-rc.2",
+    "@rollup/plugin-commonjs": "^22.0.0",
```
Comment (pi0) [inline packages/nuxt/package.json:39]: We can drop it now

File: packages/nuxt/src/core/nitro.ts (hunk 1 above)
Comment (huang-julien) [reply packages/nuxt/src/core/nitro.ts:139]: i think so, i can't figure out any case where we would need the compiler only on server-side. If the client doesn't have the runtime compiler, it would cause a difference between the dom generated by the ssr and the dom generated by the client. The client will render of the component again but without the runtime compiler, it won't be able to render the template.

File: packages/nuxt/package.json (hunk 2 above)
Comment (huang-julien) [reply packages/nuxt/package.json:39]: oops my bad

Comment (huang-julien) [reply packages/nuxt/package.json]: looks like it breaks the CI due to yarn.lock

File: packages/nuxt/src/core/nitro.ts (hunk 1 above)
Comment (huang-julien) [reply packages/nuxt/src/core/nitro.ts:139]: I just tried with the dev mode. Got a mismatch in dev mode. It needs to be supported client side in dev mode too.
```
[Vue warn]: Hydration node mismatch:
Client vnode: Symbol("Comment") 
- Server rendered DOM: 
<!-- [ -->
 (start of fragment)
 ```

**Comment by huang-julien** [comment]
it should be good now. example [here](https://github.com/huang-julien/nuxt-3/tree/feat/nuxt-ssr-runtime-template-compiler-example)

**Comment by huang-julien** [comment]
@pi0 it should be ok now. [here's](https://github.com/huang-julien/nuxt-3/tree/feat/nuxt-ssr-runtime-template-compiler-example) a working example

File: packages/nuxt/src/core/nitro.ts (hunk 1 above)
Comment (pi0) [reply packages/nuxt/src/core/nitro.ts:139]: Yes, client is fine. What i'm asking is to support **webpack** in addition to **vite** for client builds.

File: packages/schema/src/config/build.ts [hunk 3]
```diff
@@ -638,5 +638,12 @@ export default {
...
     followSymlinks: false
-  }
+  },
+
+  
+  /**
+   * enable runtime compiler on build
+   * @version 3
+   */
+   runtimeCompiler: false
```
Comment (pi0) [inline packages/schema/src/config/build.ts:648]: We might move this option under `vue` namespace

File: packages/nuxt/src/core/nitro.ts (hunk 1 above)
Comment (huang-julien) [reply packages/nuxt/src/core/nitro.ts:139]: ah yes sorry, we might need to support it if the builder used is webpack

File: packages/schema/src/config/build.ts (hunk 3 above)
Comment (huang-julien) [reply packages/schema/src/config/build.ts:648]: Since this is used in packages/nuxt/src/core/nitro.ts and packages/schema/src/config/build.ts is considered as "Legacy", can i move it to packages/schema/src/config/nitro.ts instead ?

Comment (huang-julien) [reply packages/schema/src/config/build.ts]: nervermind, vue namespace is good too :smiley:

**Comment by huang-julien** [comment]
Client builds now supports webpack and the runtimeCompiler option is now under the vue namespace in [packages/schema/src/config/_app.ts](https://github.com/nuxt/framework/commit/7095f92226a5936c26b25410a7e4935961536da3#diff-50493f2f12130c811bb1cab04babc37c120e78ffca1733b75787a41291be2bef)

**Comment by huang-julien** [comment]
@pi0 the h() function is not always used when using the runtime compiler. Devs most of the time just use the template key or write a simple object to define components, should we support it with the runtime compiler ? i can revert the commit if you want

**Comment by tobiasdiez** [comment]
What's the status of this PR? Would be awesome to use the runtime compiler soon!

**Comment by huang-julien** [comment]
@tobiasdiez if you really need it now, this [module](https://www.npmjs.com/package/nuxt-runtime-compiler) can enable it

**Comment by huang-julien** [comment]
investigating https://github.com/nuxt/framework/issues/4661#issuecomment-1182756953

**Comment by huang-julien** [comment]
fixed https://github.com/nuxt/framework/issues/4661#issuecomment-1182756953

**Comment by Atinux** [comment]
Thank you!

It would be nice to document this option somewhere since it is quite useful for CMS integrations using the template prop (see linked issue).

Also, is there a place where we can add a test case for this?

File: packages/schema/src/config/build.ts [hunk 4]
```diff
@@ -266,7 +266,7 @@ export default {
           object: 'src',
           embed: 'src'
         },
-        compilerOptions: { $resolve: (val, get) => val ?? get('vue.compilerOptions') },
+        compilerOptions: { $resolve: (val, get) => val ?? get('vue.compilerOptions') }
```
Comment (danielroe) [inline packages/schema/src/config/build.ts:269]:
```suggestion
        compilerOptions: { $resolve: (val, get) => val ?? get('vue.compilerOptions') },
```

File: packages/schema/src/config/build.ts [hunk 5]
```diff
@@ -638,5 +638,5 @@ export default {
      * @version 2
      */
     followSymlinks: false
-  }
+  },
```
Comment (danielroe) [inline packages/schema/src/config/build.ts:641]:
```suggestion
  }
```

**Comment by huang-julien** [comment]
> Also, is there a place where we can add a test case for this?

Do you mean a unit test or an example ? I've tested the  component with template defined in runtime in the playground [here](https://github.com/huang-julien/nuxt-3/tree/example/runtime-compiler)

**Comment by Atinux** [comment]
I am thinking of a test case here: https://github.com/nuxt/framework/tree/main/test

Any guidance for the best place for it? @danielroe @pi0

**Comment by pi0** [comment]
Testing requires making another fixture currently we only have one. We can add later.

I'm pending to locally test this PR. Some changes can be probably reduced for mocking and saving bundle size with option enabled.

In the meantime you can use [nuxt-runtime-compiler module](https://www.npmjs.com/package/nuxt-runtime-compiler)

**Comment by huang-julien** [comment]
Hi @danielroe , using externalVue is now working but having externalVue set to false does not work anymore (nuxt-edge/rc10). 
`Cannot find module 'D:\GIT\nuxt-3\playground\.output\server\node_modules\estree-walker\dist\esm\estree-walker.js' imported from D:\GIT\nuxt-3\playground\.output\server\chunks\renderer.mjs`

this was working on rc9.

`estree-walker/dist/umd/estree-walker.js` is still sent to `.output` but the esm dist is missing.
 
Unmocking estree-walker does not send a esm version into `.output` anymore.
https://stackblitz.com/edit/nuxt-starter-v4dnrk?file=package.json,app.vue,nuxt.config.ts,pages%2Findex.vue
````json
{
  "main": "./dist/umd/estree-walker.js",
  "module": "./dist/esm/estree-walker.js",
  "exports": {
    "require": "./dist/umd/estree-walker.js",
    "import": "./dist/esm/estree-walker.js"
  }
}
````


Should i open an issue on nitro ?

**Comment by huang-julien** [comment]
@pi0 I think test fixtures for the runtime compiler should be made with externalVue true and false since there was different issues depending on this option.

**Comment by abdonrd** [comment]
Are there plans to merge this PR? Thanks!

**Comment by huang-julien** [comment]
oh i completly forgot about this PR :sweat_smile: i'll add some tests (external vue true -- false) maybe this weekend if have some times, i also need to check if this is still working with nuxt 3.1 being released. meanwhile you can use [nuxt-runtime-compiler](https://www.npmjs.com/package/nuxt-runtime-compiler) which is basically the content of this PR but within a nuxt module

**Comment by abdonrd** [comment]
Thanks @huang-julien! The [nuxt-runtime-compiler](https://www.npmjs.com/package/nuxt-runtime-compiler) works well for us!

One thing...
We are using the `vue.compilerOptions.isCustomElement` option in the `nuxt.config.ts` as mentioned here: https://github.com/vuejs/core/issues/3746#issuecomment-835766808

(Because we are using [Katex](https://github.com/KaTeX/KaTeX))

Could it be that this configuration does not reach the runtime compiler?

**Review by danielroe — COMMENTED** [review]
Would you let me know when this ready to go? And also, would you mind redoing your last merge? I think we've ended up with a bigger diff than intended...

**Comment by huang-julien** [comment]
@danielroe about the options for vue in runtime, how should we do it ? This can be done through a plugin by the user but i think it might be better to be able to use the compatible options used at build time.

**Comment by toniengelhardt** [comment]
Having some trouble getting the module to work, but would be amazing if we could do something like this:

```vue
<script setup lang="ts">
import { compile, h } from 'vue'

const id = 5
const dc = '<div class="some-class"><MyComponent :id="${id}" /></div>'

const RenderContent = () => h(compile(dc))
</script>

<template>
  <div>
    <div>My dynamically generated content:</div>
   <RenderContent />
  </div>
</template>
```

like in these examples: 
- https://stackoverflow.com/a/70151867/1384972
- https://stackoverflow.com/questions/68981411/vue3-how-to-use-vue-compile-in-vue3

**Comment by abdonrd** [comment]
@huang-julien you have an small lint error:
https://github.com/nuxt/framework/actions/runs/4129036194/jobs/7134196036#step:6:14

**Comment by abdonrd** [comment]
@danielroe Is there still interest in merging this? Thank you!

**Comment by abdonrd** [comment]
@huang-julien it seems now the tests do not pass well.

**Comment by huang-julien** [comment]
yes estree walker is not being traced by NFT. Locally a simlink of estree walker is being send to `.output`. Going to check if this is does impact `nuxt-runtime-compiler` as well

**Comment by huang-julien** [comment]
can't find why CI are failing 🤷‍♂️ I can see logs while it does work locally. I'm not even sure if the issue comes from estree walker

File: packages/nuxt/src/core/nitro.ts [hunk 6]
```diff
@@ -163,6 +179,18 @@ export async function initNitro (nuxt: Nuxt & { _nitro?: Nitro }) {
...
+      dynamicRequireTargets: (!nuxt.options.experimental.externalVue && nuxt.options.vue.runtimeCompiler)
+        ? [
+            'node_modules/**/vue',
+            'node_modules/**/@vue/compiler-core',
+            'node_modules/**/@vue/compiler-dom',
+            'node_modules/**/@vue/compiler-ssr',
+            'node_modules/**/vue/server-renderer',
+            'node_modules/**/estree-walker'
+          ]
+        : []
```
Comment (danielroe) [inline packages/nuxt/src/core/nitro.ts:193]: is this change necessary? Tests seem to pass even when this change is omitted.

File: packages/nuxt/src/core/nitro.ts [hunk 7]
```diff
@@ -126,6 +126,18 @@ export async function initNitro (nuxt: Nuxt & { _nitro?: Nitro }) {
...
+      traceInclude: [
+        // force include files used in generated code from the runtime-compiler
+        ...(nuxt.options.vue.runtimeCompiler)
+          ? [
+              ...nuxt.options.modulesDir.reduce<string[]>((targets, path) => {
+                const serverRendererPath = resolve(path, 'vue/server-renderer/index.js')
+                if (existsSync(serverRendererPath)) { targets.push(serverRendererPath) }
+                return targets
+              }, [])
+            ]
```
Comment (danielroe) [inline packages/nuxt/src/core/nitro.ts:139]: it feels like this is only needed because of a bug in the tracing mechanism - it would be good to know if this is an issue with `vercel/nft` or with our externals plugin (cc: @pi0). Maybe because we have both estree-walker v2 and v3 installed?

File: packages/nuxt/src/core/nitro.ts (hunk 6 above)
Comment (huang-julien) [reply packages/nuxt/src/core/nitro.ts]: This is needed only when externalVue is set to false. I'll add another test :+1:

File: packages/nuxt/src/core/nitro.ts (hunk 7 above)
Comment (huang-julien) [reply packages/nuxt/src/core/nitro.ts:139]: I'm not sure if this is a bug. Since it is required by the code generated by the compiler at runtime, `vercel/nft` shouldn't be able to trace it 🤔

Comment (danielroe) [reply packages/nuxt/src/core/nitro.ts:139]: Hm. But isn't `vue/server-renderer` is required _anyway_ by Nuxt to render the server?

File: packages/nuxt/src/core/nitro.ts (hunk 6 above)
Comment (danielroe) [reply packages/nuxt/src/core/nitro.ts]: Even when setting `externalVue` to false, the runtime compiler test fixture still seems to work for me without these lines.

**Comment by autofix-troubleshooter** [comment]
Hi! I'm the <a href="https://autofix.ci">autofix logo<strong>autofix.ci</strong></a> troubleshooter bot.

It looks like you correctly set up a CI job that uses the autofix.ci GitHub Action, but the [**autofix.ci GitHub App**](https://github.com/apps/autofix-ci/) has not been installed for this repository. This means that autofix.ci unfortunately does not have the permissions to fix this pull request. If you are the repository owner, please install the app and then restart the CI workflow! 😃

File: packages/nuxt/src/core/nitro.ts (hunk 7 above)
Comment (huang-julien) [reply packages/nuxt/src/core/nitro.ts]: That's probably because the generated code use `require()` ?

File: packages/nuxt/src/core/nitro.ts (hunk 6 above)
Comment (huang-julien) [reply packages/nuxt/src/core/nitro.ts]: strange.... it should trigger some issues in build. 
I get a 
`[500] Cannot convert object to primitive value` at `ssrCompile()`

Comment (danielroe) [reply packages/nuxt/src/core/nitro.ts]: in this repository test suite? or in an external project?

Comment (huang-julien) [reply packages/nuxt/src/core/nitro.ts]: wait nvm, I did not see that the boolean has been moved to `experimental`

Comment (huang-julien) [reply packages/nuxt/src/core/nitro.ts]: I remember that this was needed at least for nuxt 3.1 🤔 but it seems that this is not needed anymore

Comment (danielroe) [reply packages/nuxt/src/core/nitro.ts]: wonderful! the best kind of code change...

**Review by danielroe — APPROVED** [review]
This looks good to me - I've tested on an external project as well, and all seems good. Very happy to iterate over v3.4 releases and then make stable in `vue.runtimeCompiler` in v3.5.

Thank you so much for your lengthy and good work on this ❤️

File: packages/nuxt/src/core/nitro.ts (hunk 7 above)
Comment (huang-julien) [reply packages/nuxt/src/core/nitro.ts]: I think this shouldn't be needed when having externalVue set to `true` 🤔

Comment (danielroe) [reply packages/nuxt/src/core/nitro.ts]: perfect!
