### ISSUE TITLE
Pinia not working

### ISSUE THREAD

**Issue by mblachlov24** [nuxt/framework#6623]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `modules`, `buildModules`, `colorMode`, `typescript`, `experimental`, `vite`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.3.2`, `@nuxtjs/color-mode@3.1.4`, `@vueuse/nuxt@9.1.0`
- Build Modules:    `@pinia/nuxt@0.4.0`

### Reproduction

I installed the pinia, added it to buildModule and got an error when starting nuxt.
It worked fine on the RC 6.

### Describe the bug

```
 ERROR  Cannot start nuxt:  Cannot find module 'pinia/dist/pinia.mjs'                                                                                                                                                10:34:41
Require stack:
- /home/nuxt3/index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:108181)
  at resolveModule (node_modules/@pinia/nuxt/node_modules/@nuxt/kit/dist/index.mjs:276:29)
  at setup (node_modules/@pinia/nuxt/dist/module.mjs:22:32)
  at Object.normalizedModule (node_modules/@pinia/nuxt/node_modules/@nuxt/kit/dist/index.mjs:607:29)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:448:3)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1495:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6768:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6813:5)
```

**Comment by 516310460** [comment]
would you please provide a reporduction?

**Comment by DamianGlowala** [comment]
Not sure if that's related, but (weirdly) I had to explicitly add `pinia` as a project dependency.

Let me know whether that works for you.

**Comment by 516310460** [comment]
> autoImports

I don't understand. I know the problem. Please provide a copy

**Comment by Lyokolux** [comment]
I updated to RC 8 with @pinia/nuxt@0.4.0 OR @pinia/nuxt@0.3.0 

I get with both the following error in development, and the project does not build anymore:
```
Error: [🍍]: getActivePinia was called with no active Pinia. Did you forget to install pinia?
	const pinia = createPinia()
	app.use(pinia)
This will fail in production.
```

**Comment by DamianGlowala** [comment]
@Lyokolux I'm getting the same error when I spin up the development server for the 'first time', but once I kill the process and start it again, the error is gone. Is it the same for you?

**Comment by Lyokolux** [comment]
> @Lyokolux I'm getting the same error when I spin up the development server for the 'first time', but once I kill the process and start it again, the error is gone. Is it the same for you?

Yes, I am currently experiencing it

**Comment by Lyokolux** [comment]
I spotted the following change in `tsconfig.json`: 
the path for pinia moved from `pinia/dist/pinia` to `node_modules/pinia/dist/pinia`

**Comment by danielroe** [comment]
Would you try clearing your `node_modules/.vite` and `node_modules/.cache` folders?

**Comment by Lyokolux** [comment]
> Would you try clearing your `node_modules/.vite` and `node_modules/.cache` folders?

It was something related to the cache because it is working now.

Updating `@pinia/nuxt` does not clean this cache, and I missed the information.

**Comment by danielroe** [comment]
Great. Let's track the root cause in https://github.com/nuxt/framework/issues/6668.

**Comment by typhoon11** [comment]
Still the same problem for me, I am not able to fix the problem with above solutions.

**Comment by Lyokolux** [comment]
> `npx nuxi-edge@latest cleanup` should also do the trick to cleanup caches.

It is not the case. I can't reproduce it on stackblitz though.

**Comment by typhoon11** [comment]
Cannot start nuxt:  Cannot find module 'pinia/dist/pinia.mjs'

**Comment by typhoon11** [comment]
> > Still the same problem for me, I am not able to fix the problem with above solutions.
> 
> What is your error?


 ERROR  Cannot start nuxt:  Cannot find module 'pinia/dist/pinia.mjs'                                                              14:10:55
Require stack:
- D:\Dashboard\frontend\index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at Function._resolve [as resolve] (node_modules\jiti\dist\jiti.js:1:243252)
  at resolveModule (/D:/Dashboard/frontend/node_modules/@nuxt/kit/dist/index.mjs:254:29)
  at setup (/D:/Dashboard/frontend/node_modules/@pinia/nuxt/dist/module.mjs:22:60)
  at Object.normalizedModule (/D:/Dashboard/frontend/node_modules/@nuxt/kit/dist/index.mjs:630:29)
  at async installModule (/D:/Dashboard/frontend/node_modules/@nuxt/kit/dist/index.mjs:449:3)
  at async initNuxt (/D:/Dashboard/frontend/node_modules/nuxt/dist/index.mjs:1553:7)
  at async load (/D:/Dashboard/frontend/node_modules/nuxi/dist/chunks/dev.mjs:6778:9)
  at async Object.invoke (/D:/Dashboard/frontend/node_modules/nuxi/dist/chunks/dev.mjs:6826:5)

**Comment by danielroe** [comment]
If you are facing an error, please raise a new issue with a reproduction. You can start from https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz.

**Comment by typhoon11** [comment]
> If you are facing an error, please raise a new issue with a reproduction. You can start from https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz.

I am not able to reporduce in the stackblitz, but it's happening to me

**Comment by CareTiger** [comment]
I am getting the same error.  - ERROR  Cannot start nuxt:  Cannot find module '@pinia/nuxt'

I tried all the above suggestions and still no fix.

**Comment by BenjaminOddou** [comment]
Also a common mistake could be that you installed `pinia` instead of `@pinia/nuxt`.

**Comment by typhoon11** [comment]
> Also a common mistake could be that you installed `pinia` instead of `@pinia/nuxt`. 

No I have installed pinia/nuxt and not pinia because you can't install pinia on nuxt 3 it gives error from npm

**Comment by BenjaminOddou** [comment]
@typhoon11, I didn't know about that feature. Maybe you can try to remove `node_modules`, `package-lock.json`, `.nuxt` and `.output`, then do a `npm i` and `npm run dev` ? 

I can just share to you my setup which is working fine :

In `package.json`
```json
  "devDependencies": {
    "@pinia/nuxt": "^0.4.2",
  }
```

In `nuxt.config.ts`
```ts
  modules: [
    '@pinia/nuxt',
  ],
```

In `composables/piniaStore.ts`
```ts
import { defineStore } from 'pinia'

export const myStore = defineStore({
  id: 'my-store',
  state: () => {
    return {
      isReady: false
    }
  }
})
```

In my application :
```ts
const test = myStore()
onMounted(() => {
  test.$patch({
    isReady: true
  })
  console.log(test.isReady)
})
```

Hope it will help. 🙂

**Comment by typhoon11** [comment]
> @typhoon11, I didn't know about that feature. Maybe you can try to remove `node_modules`, `package-lock.json`, `.nuxt` and `.output`, then do a `npm i` and `npm run dev` ? 
> 
> I can just share to you my setup which is working fine :
> 
> In `package.json`
> ```json
>   "devDependencies": {
>     "@pinia/nuxt": "^0.4.2",
>   }
> ```
> 
> In `nuxt.config.ts`
> ```ts
>   modules: [
>     '@pinia/nuxt',
>   ],
> ```
> 
> In `composables/piniaStore.ts`
> ```ts
> import { defineStore } from 'pinia'
> 
> export const myStore = defineStore({
>   id: 'my-store',
>   state: () => {
>     return {
>       isReady: false
>     }
>   }
> })
> ```
> 
> In my application :
> ```ts
> const test = myStore()
> onMounted(() => {
>   test.$patch({
>     isReady: true
>   })
>   console.log(test.isReady)
> })
> ```
> 
> Hope it will help. 🙂

I will try doing this, btw on which nuxt version you are on I am on the latest rc9

**Comment by BenjaminOddou** [comment]
I am also on rc-9. I have this config since rc-4 or 5 and didn't experience any issue

**Comment by typhoon11** [comment]
> I am also on rc-9. I have this config since rc-4 or 5 and didn't experience any issue

I did like you told but same error is coming.

Error:
![image](https://user-images.githubusercontent.com/66431066/189303262-f80b81ee-4906-481e-b35d-fd224d1d05b3.png)

Package.json
![image](https://user-images.githubusercontent.com/66431066/189303317-1ee09d93-a96f-4f29-ab3e-60a81b3a2876.png)

**Comment by BenjaminOddou** [comment]
Can you make a test on fresh nuxt app ? 🤔

**Comment by Lyokolux** [comment]
> > I am also on rc-9. I have this config since rc-4 or 5 and didn't experience any issue
> 
> I did like you told but same error is coming.
> 
> Error: ![image](https://user-images.githubusercontent.com/66431066/189303262-f80b81ee-4906-481e-b35d-fd224d1d05b3.png)
> 
> Package.json ![image](https://user-images.githubusercontent.com/66431066/189303317-1ee09d93-a96f-4f29-ab3e-60a81b3a2876.png)

Strange that you can not reproduce it on Stackblitz.
I am also using pinia, but not experiencing any issues. I have:

```
"pinia": "^2.0.18",
"@pinia/nuxt": "^0.4.2",
```

**Comment by fikurimax** [comment]
I follow this answer and run perfectly [here's the link](https://stackoverflow.com/a/72778875)

**Comment by James-Unicrypt** [comment]
I can confirm fikurmiax's stackoverflow link works. Installing pina itself (not just '@pinia/nuxt' plus --legacy-peer-deps. However this is not a good fix. Just want to add my voice here that this is broken for me aswell as of 3 days ago.

Using nuxt rc.9 or rc.10 (doesnt work on both)
and @pinia/nuxt with 

modules: [
'@pinia/nuxt'
]

in nuxt.config.ts

**Comment by BayBreezy** [comment]
Was having the same issue. 
What worked for me was installing pinia by force lol 

```bash
npm i pinia --force
```

**Comment by BenjaminOddou** [comment]
After running `npm install pinia @pinia/nuxt --legacy-peer-deps` I removed pinia with `npm uninstall pinia` and for some reason it is working great like magic 🧙‍♂️

**Comment by azelalynetan** [comment]
> After running `npm install pinia @pinia/nuxt --legacy-peer-deps` I removed pinia with `npm uninstall pinia` and for some reason it is working great like magic 🧙‍♂️

I've also experienced the same issue when installing pinia on nuxt 3 (rc.10) -> Cannot start nuxt:  Cannot find module 'pinia/dist/pinia.mjs'. I tried all the solutions above and this only works for me. Thanks!

**Comment by Keano95** [comment]
Same for me in RC10. The solution of @BayBreezy works for me. Even if I remove pinia after installing it. Strange.

**Comment by austinonchain** [comment]
@BayBreezy's solution worked for me as well lol

**Comment by senher** [comment]
> solution worked for "nuxt": "3.0.0-rc.11"，but it Still not working on "nuxt": "3.0.0-rc.10"

**Comment by senher** [comment]
> Was having the same issue. What worked for me was installing pinia by force lol
> 
> ```shell
> npm i pinia --force
> ```

solution worked for "nuxt": "3.0.0-rc.11"，but it Still not working on "nuxt": "3.0.0-rc.10"

**Comment by senher** [comment]
> Was having the same issue. What worked for me was installing pinia by force lol
> 
> ```shell
> npm i pinia --force
> ```
After I tried many times solution worked steps：
You need to remove "pinia" from package.json; （No "@pinia/nuxt"）
After run : npm i pinia --force
if you reinstall, you still need to remove "pinia" again;

**Comment by BenjaminOddou** [comment]
The problem now is that when deploying (on netlify for example) pinia is actually needed...

**Comment by m7rlin** [comment]
quickfix for now 
![image](https://user-images.githubusercontent.com/11756007/192259590-07791f89-69d1-4b27-9628-4080c672fc24.png)

**Comment by anhthang** [comment]
> The problem now is that when deploying (on netlify for example) pinia is actually needed...

yeah, it's working well for me in dev mode, but getting issue with build or deploy on vercel

**Comment by Mack-Overflow** [comment]
> After running `npm install pinia @pinia/nuxt --legacy-peer-deps` I removed pinia with `npm uninstall pinia` and for some reason it is working great like magic 🧙‍♂️

This worked for me as well after running `npm run dev -- -o`

**Comment by sebj54** [comment]
Here's what worked for me:

1. Install **only** `@pinia/nuxt` with npm or yarn
2. Add an alias in your `nuxt.config.ts` file:

```ts
export default defineNuxtConfig({
    alias: {
        pinia: 'node_modules/@pinia/nuxt/node_modules/pinia/dist/pinia.mjs',
    },
    // your config
})
```

**Comment by urbgimtam** [comment]
> Here's what worked for me:
> 
> 1. Install **only** `@pinia/nuxt` with npm or yarn
> 2. Add an alias in your `nuxt.config.ts` file:
> 
> ```ts
> export default defineNuxtConfig({
>     alias: {
>         pinia: '/node_modules/@pinia/nuxt/node_modules/pinia/dist/pinia.mjs',
>     },
>     // your config
> })
> ```

Thanks. Wasn't able to start Nuxt 3 rc 11 after installing, but this made it work.

**Comment by cerino-ligutom** [comment]
> > Here's what worked for me:
> > 
> > 1. Install **only** `@pinia/nuxt` with npm or yarn
> > 2. Add an alias in your `nuxt.config.ts` file:
> > 
> > ```ts
> > export default defineNuxtConfig({
> >     alias: {
> >         pinia: '/node_modules/@pinia/nuxt/node_modules/pinia/dist/pinia.mjs',
> >     },
> >     // your config
> > })
> > ```
> 
> Thanks. Wasn't able to start Nuxt 3 rc 11 after installing, but this made it work.

How did you make it work? This didn't work for me at all with `nuxt@3.0.0-rc.11`

![image](https://user-images.githubusercontent.com/6721822/193526274-f41f4dec-907d-4a88-8c0b-c8da42150187.png)

**Comment by sebj54** [comment]
Go to the root folder of your nuxt app, then check if you have a file at this location:

```
ls ./node_modules/@pinia/nuxt/node_modules/pinia/dist/pinia.mjs
```

Check if you have only one result for this command: `npm list pinia`. It should display something like this:

```
❯ npm list pinia
my-app@ /Users/me/projects/my-app
└─┬ @pinia/nuxt@0.4.2
  └── pinia@2.0.22
```

**Comment by cerino-ligutom** [comment]
> Go to the root folder of your nuxt app, then check if you have a file at this location:
> 
> ```
> ls ./node_modules/@pinia/nuxt/node_modules/pinia/dist/pinia.mjs
> ```
> 
> Check if you have only one result for this command: `npm list pinia`. It should display something like this:
> 
> ```
> ❯ npm list pinia
> my-app@ /Users/me/projects/my-app
> └─┬ @pinia/nuxt@0.4.2
>   └── pinia@2.0.22
> ```

idk anymore, now it's working without doing the `alias` for some reason 😅

**Comment by anhthang** [comment]
@sebj54 how do i fix with below results

```
❯ ls ./node_modules/@pinia/nuxt/node_modules/pinia/dist/pinia.mjs
ls: ./node_modules/@pinia/nuxt/node_modules/pinia/dist/pinia.mjs: No such file or directory


❯ ls ./node_modules/pinia/dist/pinia.mjs
./node_modules/pinia/dist/pinia.mjs


❯ npm list pinia
keeb-archivist@1.0.0 /Users/anhthang/Kai/keebtalogue
├─┬ @pinia/nuxt@0.4.2
│ └── pinia@2.0.22 deduped
└── pinia@2.0.22
```

**Comment by m7rlin** [comment]
try to uninstalling pinia@2.0.22
only have @pinia/nuxt@0.4.2

**Comment by u007** [comment]
i have only @pinia/nuxt and it didnt work

**Comment by AssyriaGameStudio** [comment]
I've got it working in dev now using the alias approach proposed by @sebj54 / which appears to work perfectly, however when I try and run a production build I get an error "Cannot read properties of undefined" on my store object (it builds fine, but the store seems to fail to initialise somehow?).

Anyone else running into this / have a solution?


```
export default defineNuxtConfig({
  modules: [
    [
      '@pinia/nuxt',
      { 
        autoImports: ['defineStore'],
      }
    ]
  ],

  alias: {
    pinia: '/node_modules/@pinia/nuxt/node_modules/pinia/dist/pinia.mjs',
  }
})
```

**Comment by BenjaminOddou** [comment]
@AssyriaGameStudio and if your try to delete autoimport from your nuxt config, does it work better ? 🤔

**Comment by AssyriaGameStudio** [comment]
@BenjaminOddou - sadly same issue. Runs fine in dev without autoimport, it builds fine, but when the build is run the store isn't created / is "undefined".

**Comment by AssyriaGameStudio** [comment]
For anyone experiencing the issue where it works using 'npm run dev', but not via 'npm run build'... Changing from

```
<script setup>
import { useCoreStore } from '@/stores/coreStore';
const store = useCoreStore();
</script>
```

To

```
<script>
import { useCoreStore } from '@/stores/coreStore';

export default {
  setup() {
    const store = useCoreStore();
    return { store };
  }
}
</script>
```

Seems to have fixed it for me... Not entirely clear why, but it's now all working 🤷‍♂️.

**Comment by shba007** [comment]
Removing package-lock file causes this error for me...removing package-lock then installing using npm install casues pinia add as  dependency of @pinia/nuxt which causes problem... Simply move out pinia from dependency tree of @pinia/nuxt to root dependency tree

**Comment by itsAnuga** [comment]
Started a new `Nuxt 3` project, and installed the recommended Pina module (`@pinia/nuxt`)

And got the same error as thread starter.

Removing the `.nuxt`, `node_modules` folder and package-lock.json, then re-installing the modules, solved the issue for me.

`{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
  },
  "dependencies": {
    "@pinia/nuxt": "^0.4.3",
    "nuxt": "3.0.0-rc.12"
  }
}
`

**Comment by BenjaminOddou** [comment]
> For anyone experiencing the issue where it works using 'npm run dev', but not via 'npm run build'... Changing from
> 
> 
> 
> ```
> 
> <script setup>
> 
> import { useCoreStore } from '@/stores/coreStore';
> 
> const store = useCoreStore();
> 
> </script>
> 
> ```
> 
> 
> 
> To
> 
> 
> 
> ```
> 
> <script>
> 
> import { useCoreStore } from '@/stores/coreStore';
> 
> 
> 
> export default {
> 
>   setup() {
> 
>     const store = useCoreStore();
> 
>     return { store };
> 
>   }
> 
> }
> 
> </script>
> 
> ```
> 
> 
> 
> Seems to have fixed it for me... Not entirely clear why, but it's now all working 🤷‍♂️.

@AssyriaGameStudio Did you try to put the pinia store in composables? It will allow you to skip the import syntax (probably better than the autoimport param in nuxt config)

My project is working great with the alias solution + composables. You can see here the [repo](https://github.com/BenjaminOddou/portfolio)

**Comment by Gants102** [comment]
> After running `npm install pinia @pinia/nuxt --legacy-peer-deps` I removed pinia with `npm uninstall pinia` and for some reason it is working great like magic 🧙‍♂️

Tried lots of other solutions, alias worked but then gave 500 errors in build preview when refreshing the page. Did this though and works like a charm

**Comment by reyhaneh-moayeri** [comment]
> Was having the same issue. What worked for me was installing pinia by force lol
> 
> ```shell
> npm i pinia --force
> ```

It works for me :)

**Comment by henk23** [comment]
Had the same issue with RC13. Solved it with this:

    rm -rf node_modules && rm package-lock.json && npm install

No alias, no transpile, no `npm i pinia` , no `--legacy-peer-deps`. Just `@pinia/nuxt` in package.json and `modules: ['@pinia/nuxt']` in nuxt.config.js.

**Comment by BenjaminOddou** [comment]
@henk23 no alias ? Did you try to deploy your app. I didn't had problem before deploying my app 😅

**Comment by RijaCloud** [comment]
> After running `npm install pinia @pinia/nuxt --legacy-peer-deps` I removed pinia with `npm uninstall pinia` and for some reason it is working great like magic 🧙‍♂️

Thank you @BenjaminOddou this solved the issue. It's magic

**Comment by TheKachi** [comment]
> `npx nuxi-edge@latest cleanup` should also do the trick to cleanup caches.

How do I undo this command? It's making all my config files throw an error. Even in new projects

**Comment by BenjaminOddou** [comment]
For those using autoImports option for @pinia/nuxt, take a look at [this PR](https://github.com/nuxt/framework/pull/9029) from the last rc14 version. This option is no longer supported.

**Comment by itsAnuga** [comment]
> > `npx nuxi-edge@latest cleanup` should also do the trick to cleanup caches.
> 
> How do I undo this command? It's making all my config files throw an error. Even in new projects

Make sure to have a proper commit, you can revert to.

**Comment by bachdgvn** [comment]
> 

Thank you! @henk23 
I try all solutions, all of them still works. But your way is the best.

**Comment by bastianhilton** [comment]
I ran into this issue as well, apparently the only thing I had to do was install npm i pinia and my server starts now

**Comment by dosstx** [comment]
> Had the same issue with RC13. Solved it with this:
> 
> ```
> rm -rf node_modules && rm package-lock.json && npm install
> ```
> 
> No alias, no transpile, no `npm i pinia` , no `--legacy-peer-deps`. Just `@pinia/nuxt` in package.json and `modules: ['@pinia/nuxt']` in nuxt.config.js.

Did not help. Still get "cannot find module `pinia/dist/pinia.mjs`

**Comment by dosstx** [comment]
> I ran into this issue as well, apparently the only thing I had to do was install npm i pinia and my server starts now

You should not have to install an extra pinia dependency, should only use `@pinia/nuxt`

**Comment by henk23** [comment]
I updated my comment. Also at some point hat do `npm i pinia`. Don't remember why, but needed to be done.

**Comment by BenjaminOddou** [comment]
@henk23 probably because of the pinia location in the project (it's actually included in pinia/nuxt) so

import something from 'pinia' 

can throw an error if didn't recognize as '/node_modules/@pinia/nuxt/node_modules/pinia/dist/pinia.mjs'

**Comment by samlinck** [comment]
Switching from npm to yarn did the trick for me. I had similar problems when trying to install the pinia persisted state plugin. They were also solved after the switch.

**Comment by dreamtank89** [comment]
Just sharing my experience, from what I have tried. There are 2 ways to use pinia with Nuxt. 
1. Using '@pinia/nuxt'
2. Using pinia (_this is for vue 3 not for nuxt_)

I tried the first method and my app crash big time no matter what I try to do. 

But with the 2nd method it is much more easier without any problem. 

I just run `npm install pinia --force`

Then I declare using Nuxt plugin with this setup 

```
import { createPinia } from "pinia";

export default defineNuxtPlugin((nuxtApp) => {
	const pinia = createPinia();
	nuxtApp.vueApp.use(pinia);
});
````

Then I just use pinia in my composables. 

Hope this helps

**Comment by dreamtank89** [comment]
> Just sharing my experience, from what I have tried. There are 2 ways to use pinia with Nuxt.
> 
> 1. Using '@pinia/nuxt'
> 2. Using pinia (_this is for vue 3 not for nuxt_)
> 
> I tried the first method and my app crash big time no matter what I try to do.
> 
> But with the 2nd method it is much more easier without any problem.
> 
> I just run `npm install pinia --force`
> 
> Then I declare using Nuxt plugin with this setup
> 
> ```
> import { createPinia } from "pinia";
> 
> export default defineNuxtPlugin((nuxtApp) => {
> 	const pinia = createPinia();
> 	nuxtApp.vueApp.use(pinia);
> });
> ```
> 
> Then I just use pinia in my composables.
> 
> Hope this helps

Update latest

It turns out that we need to install both package with the first and second method that I mentioned here.

**Comment by affinage-digital** [comment]
This helped in my case

```js
export default defineNuxtConfig({
    alias: {
        pinia: process.env.NODE_ENV === 'production' ? '/node_modules/pinia/dist/pinia.mjs' : '/node_modules/@pinia/nuxt/node_modules/pinia/dist/pinia.mjs',
    },
});
```

**Comment by ekawas-td** [comment]
This isn't the correct solution but I am posting it here because it worked for our app (and might help others)...

We have are using the following in our package file as dependencies:

```JSON
"@pinia/nuxt": "^0.4.6",
"pinia": "^2.0.27",
```

The app is built with `npx nuxt build`

We had the same issue as others (couldn't find the pinia module)  and `aliases` didn't help, nor did `build.transpile`. In our production dockerfile container, I ran the following copy:

```Docker
RUN cp .output/server/node_modules/pinia/dist/pinia.mjs .output/server/node_modules/pinia/dist/index.mjs
```

The app could then start up and handle requests.

**Comment by productdevbook** [comment]
```
export default defineNuxtConfig({
  imports: {
    dirs: ['stores'],
  },
    modules: [
    '@pinia/nuxt',
    ]
})
```

![image](https://user-images.githubusercontent.com/38668796/208232603-85e1ab23-9f98-45b3-a424-0f655636a316.png)


pnpm i @pinia/nuxt
pnpm i pinia


and working

**Comment by productdevbook** [comment]
```
When I restart it, it still gives an error even though it is in import.d.ts. Interesting.
```


```
export { useMap } from '../src/composables/useMap';
export { InitApp } from '../src/utils/initApp';
export { useMapStore } from '../src/stores/useMapStore';
export { useUserStore } from '../src/stores/useUserStore';
``` 

Uncaught (in promise) ReferenceError: useUserStore is not defined

**Comment by productdevbook** [comment]
> When I restart it, it still gives an error even though it is in import.d.ts. Interesting.
> 
> ```
> export { useMap } from '../src/composables/useMap';
> export { InitApp } from '../src/utils/initApp';
> export { useMapStore } from '../src/stores/useMapStore';
> export { useUserStore } from '../src/stores/useUserStore';
> ```
> 
> Uncaught (in promise) ReferenceError: useUserStore is not defined

header.vue click and ctrl + s fixed. and pnpm dev reload. Same problem go ctrl + s fixed :D

**Comment by mihul87** [comment]
Had the exact same issue `ERROR  Cannot start nuxt:  Cannot find module 'pinia/dist/pinia.mjs'`.
I'm a newbie.
I tried to reproduce the error on the https://stackblitz.com/ like Daniel said, but I couldn't.
Then I observed that the initial setup in stackblitz, it's a bit different that mine.
This scenario worked for me, up to know:
```
1.	npx nuxi init <project-name>
2.	cd <project-name>
3.	skiped npm install
4.	npm install @pinia/nuxt
5.	added Auto imports
6.	npm install
7.	npm run dev
```

**Comment by shba007** [comment]
To reliably solve this problem you can do this following steps:
1. Open package-lock.json
2. Find `"node_modules/@pinia/nuxt/node_modules/pinia"` this package
3. Rename `"node_modules/@pinia/nuxt/node_modules/pinia"` -> `"node_modules/pinia"`
4. Remove `node-modules` , run `nuxt cleanup` and `npm install`
5. Now run `nuxt dev`

This problem occurs in npm not yarn, if you run `npm update` it will reoccur this you have to re do the steps
